### PR TITLE
Hot fix/collabrators names correction

### PR DESCRIPTION
**Pull request by sagarc03**
Adds a fix for the issue described in issue #10 Correct collaborators names in readme.md

### CODE REVIEW

**Comment by sangar-happy** [comment]
Hey @sagarc03 did you check the preview of the file? I think the names will still be in a single line. Maybe a blank line is to be inserted in between.

**Comment by sangar-happy** [comment]
I'm not authorized to merge the pull requests.

**Comment by sagarc03** [comment]
Are you sure? Did you try to approve it?

**Comment by sangar-happy** [comment]
[proof](https://imgur.com/a/snz6Mqj)

**Pull request merged**
